#!/usr/bin/env python
"""
Streamlit app for interactive 3D visualization of stellarator coils and
plasma surface.  Reads VTU/VTS files generated by example_1_case.py.

Run with:
    streamlit run streamlit_coils.py
"""

import numpy as np
import plotly.graph_objects as go
import pyvista as pv
import streamlit as st
from pathlib import Path

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Coil Viewer", layout="wide")
st.title("🌀 Stellarator Coil Viewer")

OUT_DIR = Path(__file__).parent / "output_pytorch_rotated"

COLORS = [
    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
    "#9467bd", "#8c564b", "#e377c2", "#7f7f7f",
    "#bcbd22", "#17becf", "#aec7e8", "#ffbb78",
    "#98df8a", "#ff9896", "#c5b0d5", "#c49c94",
]


# ---------------------------------------------------------------------------
# I/O helpers (cached so files are only read once per combination)
# ---------------------------------------------------------------------------
@st.cache_data
def load_coils_from_vtu(filepath: str) -> list[np.ndarray]:
    """Return a list of (N,3) arrays – one per coil."""
    mesh = pv.read(filepath)
    points = np.array(mesh.points)
    coils = []
    for i in range(mesh.n_cells):
        cell = mesh.get_cell(i)
        coils.append(points[cell.point_ids])
    return coils


@st.cache_data
def load_surface_from_vts(filepath: str):
    """Return (points, triangles, b_n) from a structured‑grid surface file."""
    mesh = pv.read(filepath)
    surf = mesh.extract_surface()
    points = np.array(surf.points)
    faces = surf.faces

    b_n = None
    for name in surf.point_data:
        if "b_n" in name.lower():
            b_n = np.array(surf.point_data[name]).flatten()
            break

    triangles = []
    idx = 0
    while idx < len(faces):
        n = faces[idx]
        verts = faces[idx + 1 : idx + 1 + n]
        if n == 3:
            triangles.append(verts)
        elif n == 4:
            triangles.append([verts[0], verts[1], verts[2]])
            triangles.append([verts[0], verts[2], verts[3]])
        idx += 1 + n

    triangles = np.array(triangles) if triangles else None
    return points, triangles, b_n


def available_stages(out_dir: Path) -> list[str]:
    """Discover which stages (init, opt, …) have curves files."""
    stages = set()
    for f in out_dir.glob("curves_*.vtu"):
        name = f.stem  # e.g. curves_opt or curves_opt_3
        parts = name.split("_")
        # "curves_opt.vtu"  -> parts = ["curves", "opt"]
        # "curves_opt_3.vtu" -> parts = ["curves", "opt", "3"]
        if len(parts) >= 2:
            stages.add(parts[1])
    return sorted(stages)


def count_perturbed(out_dir: Path, stage: str) -> int:
    return len(list(out_dir.glob(f"curves_{stage}_*.vtu")))


# ---------------------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------------------
stages = available_stages(OUT_DIR)
if not stages:
    st.error(f"No curve files found in `{OUT_DIR}`. Run `example_1_case.py` first.")
    st.stop()

with st.sidebar:
    st.header("Settings")

    stage = st.selectbox("Stage", stages, index=stages.index("opt") if "opt" in stages else 0)

    show_surface = st.checkbox("Show plasma surface", value=True)
    surface_opacity = st.slider("Surface opacity", 0.0, 1.0, 0.45, 0.05)
    coil_width = st.slider("Coil line width", 1, 12, 6)

    n_pert_available = count_perturbed(OUT_DIR, stage)
    show_perturbed = False
    n_pert = 0
    if n_pert_available > 0:
        show_perturbed = st.checkbox(
            f"Show perturbed coils ({n_pert_available} available)", value=False
        )
        if show_perturbed:
            n_pert = st.slider(
                "Max perturbed samples", 1, min(n_pert_available, 16), min(3, n_pert_available)
            )

    dark_mode = st.checkbox("Dark background", value=True)

    st.divider()
    st.subheader("Unique Shape Groups")
    n_unique_shapes = st.number_input(
        "Number of unique coil shapes (Q)",
        min_value=1, max_value=32, value=1, step=1,
        help="Must match n_unique_shapes used during optimization. "
             "Coils are assigned to shape groups cyclically: coil i → group (i mod Q).",
    )
    color_by_group = st.checkbox("Color coils by shape group", value=True)

    st.divider()
    overlay_coils = st.checkbox("🔍 Overlay coils (shape comparison)", value=False)

    # Compare two stages side‑by‑side
    compare = False
    stage_b = stage
    if len(stages) > 1:
        compare = st.checkbox("Compare two stages side‑by‑side", value=False)
        if compare:
            other = [s for s in stages if s != stage]
            stage_b = st.selectbox("Second stage", other, index=0)


# ---------------------------------------------------------------------------
# Build figure
# ---------------------------------------------------------------------------
# Shape-group color palette (distinct colors per group)
GROUP_COLORS = [
    "#e6194b", "#3cb44b", "#4363d8", "#f58231",
    "#911eb4", "#42d4f4", "#f032e6", "#bfef45",
    "#fabed4", "#469990", "#dcbeff", "#9A6324",
    "#fffac8", "#800000", "#aaffc3", "#808000",
]


def build_figure(stage, show_surface, surface_opacity, coil_width,
                 show_perturbed, n_pert, dark_mode,
                 n_unique_shapes=1, color_by_group=True):
    fig = go.Figure()

    # Main coils
    curves_file = OUT_DIR / f"curves_{stage}.vtu"
    coils = load_coils_from_vtu(str(curves_file))

    for i, pts in enumerate(coils):
        group = i % n_unique_shapes
        if color_by_group:
            color = GROUP_COLORS[group % len(GROUP_COLORS)]
        else:
            color = COLORS[i % len(COLORS)]
        group_label = f" [shape {group + 1}]" if n_unique_shapes > 1 else ""
        xyz = np.concatenate([pts, pts[:1]], axis=0)
        fig.add_trace(
            go.Scatter3d(
                x=xyz[:, 0], y=xyz[:, 1], z=xyz[:, 2],
                mode="lines",
                line=dict(width=coil_width, color=color),
                name=f"Coil {i + 1}{group_label}",
            )
        )

    # Perturbed coils
    if show_perturbed:
        pert_files = sorted(OUT_DIR.glob(f"curves_{stage}_*.vtu"))
        for idx, pf in enumerate(pert_files[:n_pert]):
            pert_coils = load_coils_from_vtu(str(pf))
            for j, pts in enumerate(pert_coils):
                xyz = np.concatenate([pts, pts[:1]], axis=0)
                fig.add_trace(
                    go.Scatter3d(
                        x=xyz[:, 0], y=xyz[:, 1], z=xyz[:, 2],
                        mode="lines",
                        line=dict(width=2, color="rgba(150,150,150,0.3)"),
                        name=f"Pert {idx}" if j == 0 else None,
                        showlegend=(j == 0),
                    )
                )

    # Plasma surface
    surf_file = OUT_DIR / f"surf_{stage}.vts"
    if show_surface and surf_file.exists():
        pts, tris, b_n = load_surface_from_vts(str(surf_file))
        if tris is not None and len(tris) > 0:
            kw = dict(
                x=pts[:, 0], y=pts[:, 1], z=pts[:, 2],
                i=tris[:, 0], j=tris[:, 1], k=tris[:, 2],
                opacity=surface_opacity,
                name="Plasma surface",
                showlegend=True,
            )
            if b_n is not None and len(b_n) == len(pts):
                bmax = np.max(np.abs(b_n))
                kw.update(
                    intensity=b_n, colorscale="RdBu",
                    cmin=-bmax, cmax=bmax,
                    colorbar=dict(title="B·n"),
                )
            fig.add_trace(go.Mesh3d(**kw))

    bg = "rgb(20,20,20)" if dark_mode else "white"
    paper = "rgb(30,30,30)" if dark_mode else "white"
    font_color = "white" if dark_mode else "black"

    shape_info = f" ({n_unique_shapes} unique shape{'s' if n_unique_shapes > 1 else ''})" if n_unique_shapes > 1 else ""
    fig.update_layout(
        title=f"Stellarator Coils & Plasma Surface — {stage}{shape_info}",
        scene=dict(
            xaxis_title="X [m]", yaxis_title="Y [m]", zaxis_title="Z [m]",
            aspectmode="data",
            bgcolor=bg,
        ),
        legend=dict(x=0.01, y=0.99),
        margin=dict(l=0, r=0, t=40, b=0),
        paper_bgcolor=paper,
        font=dict(color=font_color),
    )
    return fig, len(coils)


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------
if compare:
    col1, col2 = st.columns(2)
    with col1:
        st.subheader(f"Stage: {stage}")
        fig_a, n_a = build_figure(stage, show_surface, surface_opacity,
                                  coil_width, show_perturbed, n_pert, dark_mode,
                                  n_unique_shapes, color_by_group)
        st.plotly_chart(fig_a, use_container_width=True)
        st.caption(f"{n_a} coils loaded · {n_unique_shapes} unique shape(s)")
    with col2:
        st.subheader(f"Stage: {stage_b}")
        fig_b, n_b = build_figure(stage_b, show_surface, surface_opacity,
                                  coil_width, False, 0, dark_mode,
                                  n_unique_shapes, color_by_group)
        st.plotly_chart(fig_b, use_container_width=True)
        st.caption(f"{n_b} coils loaded · {n_unique_shapes} unique shape(s)")
else:
    fig, n_coils = build_figure(stage, show_surface, surface_opacity,
                                coil_width, show_perturbed, n_pert, dark_mode,
                                n_unique_shapes, color_by_group)
    st.plotly_chart(fig, use_container_width=True)
    st.caption(f"{n_coils} coils loaded from `curves_{stage}.vtu` · {n_unique_shapes} unique shape(s)")


# ---------------------------------------------------------------------------
# Coil overlay / shape comparison
# ---------------------------------------------------------------------------
def _align_procrustes(reference: np.ndarray, target: np.ndarray) -> np.ndarray:
    """Align *target* to *reference* using Procrustes (optimal rotation).

    Both arrays must be centred (mean‑subtracted) and have the same shape
    (N, 3).  Returns the rotated target.
    """
    H = target.T @ reference  # 3×3
    U, _, Vt = np.linalg.svd(H)
    # Correct for reflection
    d = np.linalg.det(Vt.T @ U.T)
    S = np.diag([1, 1, np.sign(d)])
    R = Vt.T @ S @ U.T
    return target @ R.T


def _best_circular_shift(reference: np.ndarray, target: np.ndarray) -> int:
    """Find the circular shift of *target* that minimises RMSD to *reference*
    after Procrustes alignment.  Tries every shift (and the reversed curve)
    and returns (shifted+aligned array, rmsd).
    """
    n = len(target)
    best_rmsd = np.inf
    best_result = target.copy()

    for arr in [target, target[::-1]]:  # also try reversed direction
        for shift in range(n):
            rolled = np.roll(arr, shift, axis=0)
            aligned = _align_procrustes(reference, rolled)
            rmsd = np.sqrt(np.mean(np.sum((aligned - reference) ** 2, axis=1)))
            if rmsd < best_rmsd:
                best_rmsd = rmsd
                best_result = aligned

    return best_result, best_rmsd


def build_overlay_figure(stage, coil_width, dark_mode, n_unique_shapes=1):
    """Build a figure with coils centred + aligned, grouped by shape.

    With Q unique shapes the overlay compares coils *within* each shape
    group separately.
    """
    curves_file = OUT_DIR / f"curves_{stage}.vtu"
    coils = load_coils_from_vtu(str(curves_file))

    if len(coils) == 0:
        return go.Figure(), 0, []

    # Resample each coil to the same number of points so shifts work
    n_pts = min(len(c) for c in coils)

    centred: list[np.ndarray] = []
    for c in coils:
        if len(c) != n_pts:
            idx = np.round(np.linspace(0, len(c) - 1, n_pts)).astype(int)
            c = c[idx]
        centroid = c.mean(axis=0)
        centred.append(c - centroid)

    # Group coils by shape index (coil i belongs to group i % Q)
    groups: dict[int, list[int]] = {}
    for i in range(len(coils)):
        g = i % n_unique_shapes
        groups.setdefault(g, []).append(i)

    fig = go.Figure()
    all_rmsds: list[float] = [0.0] * len(coils)
    group_labels: list[str] = [""] * len(coils)

    for g, members in sorted(groups.items()):
        ref_idx = members[0]
        ref = centred[ref_idx]
        group_color = GROUP_COLORS[g % len(GROUP_COLORS)]

        for rank, ci in enumerate(members):
            if ci == ref_idx:
                pts = ref
                rmsd = 0.0
            else:
                pts, rmsd = _best_circular_shift(ref, centred[ci])
            all_rmsds[ci] = rmsd
            group_labels[ci] = f"shape {g + 1}"

            xyz = np.concatenate([pts, pts[:1]], axis=0)
            label = f"Coil {ci + 1} [shape {g + 1}]  (RMSD {rmsd:.4f})"
            fig.add_trace(
                go.Scatter3d(
                    x=xyz[:, 0], y=xyz[:, 1], z=xyz[:, 2],
                    mode="lines",
                    line=dict(width=coil_width, color=group_color),
                    name=label,
                )
            )

    bg = "rgb(20,20,20)" if dark_mode else "white"
    paper = "rgb(30,30,30)" if dark_mode else "white"
    font_color = "white" if dark_mode else "black"

    title_suffix = (
        f"  ({n_unique_shapes} shape groups, aligned within each group)"
        if n_unique_shapes > 1
        else "  (aligned to Coil 1)"
    )
    fig.update_layout(
        title=f"Coil Shape Overlay — {stage}{title_suffix}",
        scene=dict(
            xaxis_title="X", yaxis_title="Y", zaxis_title="Z",
            aspectmode="data",
            bgcolor=bg,
        ),
        legend=dict(x=0.01, y=0.99),
        margin=dict(l=0, r=0, t=40, b=0),
        paper_bgcolor=paper,
        font=dict(color=font_color),
    )
    return fig, len(coils), all_rmsds, group_labels


if overlay_coils:
    st.divider()
    st.subheader("🔍 Coil Shape Overlay")
    if n_unique_shapes > 1:
        st.markdown(
            f"Coils are grouped into **{n_unique_shapes} shape groups** "
            "(assigned cyclically: coil *i* → group *i* mod *Q*).  "
            "Within each group, coils are centred and Procrustes-aligned "
            "to the first member.  Coils sharing a shape should overlap perfectly."
        )
    else:
        st.markdown(
            "Each coil is centred at the origin and optimally rotated "
            "(Procrustes alignment) to match **Coil 1**.  "
            "If all coils are identical shapes the traces will overlap perfectly."
        )
    overlay_fig, n_overlay, rmsds, group_labels = build_overlay_figure(
        stage, coil_width, dark_mode, n_unique_shapes
    )
    st.plotly_chart(overlay_fig, use_container_width=True)

    # Show RMSD table
    if rmsds:
        import pandas as pd
        df = pd.DataFrame({
            "Coil": [f"Coil {i+1}" for i in range(len(rmsds))],
            "Shape Group": group_labels,
            "RMSD vs group reference": [f"{r:.6f}" for r in rmsds],
        })
        st.dataframe(df, hide_index=True, use_container_width=False)
