#!/usr/bin/env python
"""
Interactive 3D visualization of coils and plasma surface using Plotly.
Reads VTU/VTS files generated by example_1_case.py via pyvista (VTK).

Usage:
    python plotting_coils.py              # plots "opt" stage by default
    python plotting_coils.py init         # plots "init" stage
    python plotting_coils.py opt 5        # plots opt stage, max 5 perturbed samples
"""

import sys
import numpy as np
import plotly.graph_objects as go
import pyvista as pv
from pathlib import Path

# === Configuration ===
OUT_DIR = Path(__file__).parent / "output"
STAGE = sys.argv[1] if len(sys.argv) > 1 else "opt"
MAX_PERTURBED = int(sys.argv[2]) if len(sys.argv) > 2 else 3

COLORS = [
    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
    "#9467bd", "#8c564b", "#e377c2", "#7f7f7f",
    "#bcbd22", "#17becf", "#aec7e8", "#ffbb78",
    "#98df8a", "#ff9896", "#c5b0d5", "#c49c94",
]


def load_coils_from_vtu(filepath):
    """Read a curves VTU file with pyvista and return a list of (N,3) arrays,
    one per coil."""
    mesh = pv.read(str(filepath))
    points = np.array(mesh.points)

    # simsopt stores each coil as a separate cell of type POLY_LINE or LINE
    coils = []
    if mesh.n_cells == 0:
        return coils

    for i in range(mesh.n_cells):
        cell = mesh.get_cell(i)
        ids = cell.point_ids
        pts = points[ids]
        coils.append(pts)

    return coils


def load_surface_from_vts(filepath):
    """Read a surface VTS file with pyvista and return points + B_N data."""
    mesh = pv.read(str(filepath))
    # .vts is a StructuredGrid – extract surface as polydata for triangulation
    surf = mesh.extract_surface()
    points = np.array(surf.points)
    faces = surf.faces  # pyvista face array: [n, id0, id1, ..., n, id0, ...]

    # Extract B_N if available
    b_n = None
    for name in surf.point_data:
        if "B_N" in name or "b_n" in name.lower():
            b_n = np.array(surf.point_data[name]).flatten()
            break

    # Convert pyvista face array to triangle indices
    triangles = []
    idx = 0
    while idx < len(faces):
        n_verts = faces[idx]
        vert_ids = faces[idx + 1 : idx + 1 + n_verts]
        if n_verts == 3:
            triangles.append(vert_ids)
        elif n_verts == 4:
            triangles.append([vert_ids[0], vert_ids[1], vert_ids[2]])
            triangles.append([vert_ids[0], vert_ids[2], vert_ids[3]])
        idx += 1 + n_verts

    triangles = np.array(triangles) if triangles else None
    return points, triangles, b_n


# === Build figure ===
fig = go.Figure()

# --- Main coils ---
curves_file = OUT_DIR / f"curves_{STAGE}.vtu"
if not curves_file.exists():
    print(f"ERROR: {curves_file} not found.")
    print(f"Available files in {OUT_DIR}:")
    for f in sorted(OUT_DIR.iterdir()):
        print(f"  {f.name}")
    sys.exit(1)

print(f"Loading coils from {curves_file}")
coils = load_coils_from_vtu(curves_file)
print(f"  Found {len(coils)} coils")

for i, pts in enumerate(coils):
    # Close the loop
    xyz = np.concatenate([pts, pts[:1]], axis=0)
    color = COLORS[i % len(COLORS)]
    fig.add_trace(
        go.Scatter3d(
            x=xyz[:, 0], y=xyz[:, 1], z=xyz[:, 2],
            mode="lines",
            line=dict(width=6, color=color),
            name=f"Coil {i + 1}",
        )
    )

# --- Perturbed coil samples (semi-transparent overlay) ---
pert_files = sorted(OUT_DIR.glob(f"curves_{STAGE}_*.vtu"))
for idx, pf in enumerate(pert_files[:MAX_PERTURBED]):
    print(f"Loading perturbed coils from {pf.name}")
    pert_coils = load_coils_from_vtu(pf)
    for pts in pert_coils:
        xyz = np.concatenate([pts, pts[:1]], axis=0)
        fig.add_trace(
            go.Scatter3d(
                x=xyz[:, 0], y=xyz[:, 1], z=xyz[:, 2],
                mode="lines",
                line=dict(width=2, color="rgba(150,150,150,0.3)"),
                name=f"Pert {idx}" if pts is pert_coils[0] else None,
                showlegend=(pts is pert_coils[0]),
            )
        )

# --- Plasma surface ---
surf_file = OUT_DIR / f"surf_{STAGE}.vts"
if surf_file.exists():
    print(f"Loading surface from {surf_file}")
    pts, tris, b_n = load_surface_from_vts(surf_file)

    if tris is not None and len(tris) > 0:
        surf_kwargs = dict(
            x=pts[:, 0], y=pts[:, 1], z=pts[:, 2],
            i=tris[:, 0], j=tris[:, 1], k=tris[:, 2],
            opacity=0.45,
            name="Plasma surface",
            showlegend=True,
        )
        if b_n is not None and len(b_n) == len(pts):
            bmax = np.max(np.abs(b_n))
            surf_kwargs.update(
                intensity=b_n,
                colorscale="RdBu",
                cmin=-bmax, cmax=bmax,
                colorbar=dict(title="B·n"),
            )
        fig.add_trace(go.Mesh3d(**surf_kwargs))
        print(f"  Surface: {len(pts)} points, {len(tris)} triangles")
    else:
        print("  Warning: no triangles extracted from surface file")
else:
    print(f"Warning: {surf_file} not found, skipping surface plot.")

# === Layout ===
fig.update_layout(
    title=f"Stellarator Coils & Plasma Surface ({STAGE})",
    scene=dict(
        xaxis_title="X [m]",
        yaxis_title="Y [m]",
        zaxis_title="Z [m]",
        aspectmode="data",
        bgcolor="rgb(20, 20, 20)",
    ),
    legend=dict(x=0.01, y=0.99),
    width=1100,
    height=850,
    paper_bgcolor="rgb(30, 30, 30)",
    font=dict(color="white"),
)

fig.show()